port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "BoyZin"
bind-address: "https://bit.ly/m/Netsabay-Cambodia"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
    
proxies:

  - name: ğŸ‡°ğŸ‡­V2-MLBB1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 584c972c-b60f-11ee-bcf1-df6481b0e1af
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡°ğŸ‡­V2-MLBB2
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: e85908ce-b03c-11ee-a5be-7f89090aca8a
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true
  
  - name: ğŸ‡°ğŸ‡­V2-MLBB3
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 86cb189a-a268-11ee-9fa8-e3b5cfde3319
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡°ğŸ‡­V2-MLBB4
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 6ea104be-a268-11ee-96fc-cf844362dbec
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡¸ğŸ‡¬V2-MLBB5
    server: 103.253.24.221
    port: 443
    type: vmess
    uuid: e620d600-ee19-4012-a96c-968e85a52de9
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /sshkit/1229251110/65444c9c47aa4/
      headers:
        Host: m.mobilelegends.com
    udp: false

  - name: ğŸ‡¸ğŸ‡¬V2-MLBB6
    server: 45.12.80.144
    port: 10000
    type: vmess
    uuid: 64d60e60-a269-11ee-b9f5-00163e0c1be4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡¸ğŸ‡¬TJ-MLBB1
    type: trojan
    server: 149.28.131.42
    port: 443
    password: opentunnel.net-mwtgrj
    ws: false
    udp: true
    skip-cert-verify: true
    ws-path: /
    sni: m.mobilelegends.com
    alpn:

  - name: ğŸ‡¸ğŸ‡¬TJ-MLBB2
    type: trojan
    server: 103.253.24.212
    port: 443
    password: 50cb5280-9b04-11ee-88fd-1239d0255272
    ws: false
    udp: true
    skip-cert-verify: true
    ws-path: /howdy
    sni: m.mobilelegends.com
    alpn:

  - name: ğŸ‡¸ğŸ‡¬SS-MLBB1
    type: ss
    server: sg-ss.sshmax.xyz
    port: 8139
    cipher: chacha20-ietf-poly1305
    password: ZGE5MjEz
    plugin: obfs
    plugin-opts:
       mode: http
       host: m.mobilelegends.com

  - name: ğŸ‡°ğŸ‡­V2-PUBG1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 5004ac72-a268-11ee-8cf6-cb97b6daa7d4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: www.pubgmobile.com
    udp: true

  - name: ğŸ‡°ğŸ‡­V2-FREE1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: a5dcd682-a9d0-11ee-91f0-9bac6ac0bf07
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.freefiremobile.com

  - name: ğŸ‡°ğŸ‡­V2-TIK TOK1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 2cd3f51e-a268-11ee-bc0e-4398c11dcea6
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: www.tiktok.com

  - name: ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 2cd3f51e-a268-11ee-bc0e-4398c11dcea6
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.line.me

  - name: ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 2cd3f51e-a268-11ee-bc0e-4398c11dcea6
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
        
proxy-groups:
  - name: ğŸ”° Server List
    type: select
    proxies:
      - ğŸ®MLBB PROMO
      - ğŸ®PUBG MOBILE
      - ğŸ®FREE FIRE
      - ğŸ”°TIK TOK
      - ğŸ”°SOCIAL PACK
      - ğŸ”°MLBB Ã— Tik Tok Metfone
  - name: ğŸ®MLBB PROMO
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-MLBB1
      - ğŸ‡°ğŸ‡­V2-MLBB2
      - ğŸ‡°ğŸ‡­V2-MLBB3
      - ğŸ‡°ğŸ‡­V2-MLBB4
      - ğŸ‡¸ğŸ‡¬V2-MLBB5
      - ğŸ‡¸ğŸ‡¬V2-MLBB6
      - ğŸ‡¸ğŸ‡¬TJ-MLBB1
      - ğŸ‡¸ğŸ‡¬TJ-MLBB2
      - ğŸ‡¸ğŸ‡¬SS-MLBB1
  - name: ğŸ®PUBG MOBILE 
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-PUBG1
  - name: ğŸ®FREE FIRE
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-FREE1
  - name: ğŸ”°TIK TOK
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-TIK TOK1
  - name: ğŸ”°SOCIAL PACK
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
  - name: ğŸ”°MLBB Ã— Tik Tok Metfone
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
  - name: PROXY ğŸš€
    type: select
    proxies:
      - PROXY AUTOâ™»ï¸
      - ğŸ‡°ğŸ‡­V2-MLBB1
      - ğŸ‡°ğŸ‡­V2-PUBG1
      - ğŸ‡°ğŸ‡­V2-FREE1
      - ğŸ‡°ğŸ‡­V2-TIK TOK1
      - ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
      - ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: Auto-Fallback ğŸŒ€
    type: fallback
    proxies:
      - ğŸ‡°ğŸ‡­V2-MLBB1
      - ğŸ‡°ğŸ‡­V2-PUBG1
      - ğŸ‡°ğŸ‡­V2-FREE1
      - ğŸ‡°ğŸ‡­V2-TIK TOK1
      - ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
      - ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: PROXY AUTOâ™»ï¸
    type: url-test
    proxies:
      - ğŸ‡°ğŸ‡­V2-MLBB1
      - ğŸ‡°ğŸ‡­V2-PUBG1
      - ğŸ‡°ğŸ‡­V2-FREE1
      - ğŸ‡°ğŸ‡­V2-TIK TOK1
      - ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
      - ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: â™»ï¸AUTO
    type: url-test
    proxies:
      - ğŸ‡°ğŸ‡­V2-MLBB1
      - ğŸ‡°ğŸ‡­V2-PUBG1
      - ğŸ‡°ğŸ‡­V2-FREE1
      - ğŸ‡°ğŸ‡­V2-TIK TOK1
      - ğŸ‡°ğŸ‡­V2-SOCIAL PACK1
      - ğŸ‡°ğŸ‡­V2-MLBB Ã— Tik Tok1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,IR,DIRECT
  - MATCH,ğŸ”° Server List
  - IP-CIDR,1.3.0.0/8,ğŸ”° Server List
  - IP-CIDR,1.0.1.0/16,ğŸ”° Server List
  - IP-CIDR,1.0.8.0/18,ğŸ”° Server List
  - IP-CIDR,1.2.0.0/32,ğŸ”° Server List
  - MATCH,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.3.0.0/8,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.0.1.0/16,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.0.8.0/18,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.2.0.0/32,Auto-Fallback ğŸŒ€
