port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
    
proxies:

  - name: ğŸ‡°ğŸ‡­KH1-MLBB
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: da6aa386-6e91-11ee-a297-6fd6e2269234
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡°ğŸ‡­KH2-MLBB
    server: 220.158.233.184
    port: 10000
    type: vmess
    uuid: 83a83f7c-6e91-11ee-af3f-2304325531c8
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true
  
  - name: ğŸ‡°ğŸ‡­KH3-MLBB
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: d3dfc20c-6e92-11ee-bf1e-27735f3ab932
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡°ğŸ‡­KH4-MLBB
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: 220f5d74-6e94-11ee-8233-eb733def1097
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.mobilelegends.com
    udp: true

  - name: ğŸ‡¸ğŸ‡¬SG3-MLBB
    type: trojan
    server: 149.28.131.42
    port: 443
    password: opentunnel.net-gsryip
    ws: false
    udp: true
    skip-cert-verify: true
    ws-path: /
    sni: m.mobilelegends.com
    alpn:

  - name: ğŸ‡¸ğŸ‡¬SG4-MLBB
    type: trojan
    server: 103.253.24.77
    port: 443
    password: 1f6d2340-5f39-11ee-9f33-1239d0255272
    ws: false
    udp: true
    skip-cert-verify: true
    ws-path: /howdy
    sni: m.mobilelegends.com
    alpn:

  - name: ğŸ‡¸ğŸ‡¬SG5-MLBB
    type: ss
    server: 51.79.207.10
    port: 8139
    cipher: chacha20-ietf-poly1305
    password: Yzc2N
    plugin: obfs
    plugin-opts:
       mode: http
       host: m.mobilelegends.com

  - name: ğŸ‡°ğŸ‡­KH1-PUBG
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: 89cafc98-691c-11ee-a9ed-8372d3f4827e
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: www.pubgmobile.com
    udp: true

  - name: ğŸ‡°ğŸ‡­KH1-FREE
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: 89cafc98-691c-11ee-a9ed-8372d3f4827e
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.freefiremobile.com

  - name: ğŸ‡°ğŸ‡­KH1-TIK TOK
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: 89cafc98-691c-11ee-a9ed-8372d3f4827e
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: www.tiktok.com

  - name: ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
    server: 220.158.233.91
    port: 10000
    type: vmess
    uuid: 89cafc98-691c-11ee-a9ed-8372d3f4827e
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: m.mobilelegends.com
    network: ws
    ws-opts:
      path: /vpnjantit
      headers:
        Host: m.line.me
        
proxy-groups:
  - name: ğŸ”° Server List
    type: select
    proxies:
      - ğŸ®MLBB PROMO
      - ğŸ®PUBG MOBILE
      - ğŸ®FREE FIRE
      - ğŸ”°TIK TOK
      - ğŸ”°SOCIAL PACK
  - name: ğŸ®MLBB PROMO
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­KH1-MLBB
      - ğŸ‡°ğŸ‡­KH2-MLBB
      - ğŸ‡°ğŸ‡­KH3-MLBB
      - ğŸ‡°ğŸ‡­KH4-MLBB
      - ğŸ‡¸ğŸ‡¬SG3-MLBB
      - ğŸ‡¸ğŸ‡¬SG4-MLBB
      - ğŸ‡¸ğŸ‡¬SG5-MLBB
  - name: ğŸ®PUBG MOBILE 
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­KH1-PUBG
  - name: ğŸ®FREE FIRE
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­KH1-FREE
  - name: ğŸ”°TIK TOK
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­KH1-TIK TOK
  - name: ğŸ”°SOCIAL PACK
    type: select
    proxies:
      - ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
  - name: PROXY ğŸš€
    type: select
    proxies:
      - PROXY AUTOâ™»ï¸
      - ğŸ‡°ğŸ‡­KH1-MLBB
      - ğŸ‡°ğŸ‡­KH1-PUBG
      - ğŸ‡°ğŸ‡­KH1-FREE
      - ğŸ‡°ğŸ‡­KH1-TIK TOK
      - ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: Auto-Fallback ğŸŒ€
    type: fallback
    proxies:
      - ğŸ‡°ğŸ‡­KH1-MLBB
      - ğŸ‡°ğŸ‡­KH1-PUBG
      - ğŸ‡°ğŸ‡­KH1-FREE
      - ğŸ‡°ğŸ‡­KH1-TIK TOK
      - ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: PROXY AUTOâ™»ï¸
    type: url-test
    proxies:
      - ğŸ‡°ğŸ‡­KH1-MLBB
      - ğŸ‡°ğŸ‡­KH1-PUBG
      - ğŸ‡°ğŸ‡­KH1-FREE
      - ğŸ‡°ğŸ‡­KH1-TIK TOK
      - ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: â™»ï¸AUTO
    type: url-test
    proxies:
      - ğŸ‡°ğŸ‡­KH1-MLBB
      - ğŸ‡°ğŸ‡­KH1-PUBG
      - ğŸ‡°ğŸ‡­KH1-FREE
      - ğŸ‡°ğŸ‡­KH1-TIK TOK
      - ğŸ‡°ğŸ‡­KH1-SOCIAL PACK
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - DOMAIN-SUFFIX,ad.com,REJECT
  - GEOIP,IR,DIRECT
  - MATCH,ğŸ”° Server List
  - IP-CIDR,1.3.0.0/8,ğŸ”° Server List
  - IP-CIDR,1.0.1.0/16,ğŸ”° Server List
  - IP-CIDR,1.0.8.0/18,ğŸ”° Server List
  - IP-CIDR,1.2.0.0/32,ğŸ”° Server List
  - MATCH,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.3.0.0/8,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.0.1.0/16,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.0.8.0/18,Auto-Fallback ğŸŒ€
  - IP-CIDR,1.2.0.0/32,Auto-Fallback ğŸŒ€
